name: CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 14.20.1
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn build
