name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 14.20.1
      - name: Install yarn
        run: npm install -g yarn
      - name: Installing deps
        run: yarn install
      - name: Generate next build
        run: yarn build
      #share artifact between workflow
      - name: Share artifact between workflows
        uses: actions/upload-artifact@v1
        with:
          name: nextjs-build
          path: .next
  web-deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      # Download previously shared build
      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: nextjs-build

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp.ptriskyputrakasih.com
          username: app.ptriskyputrakasih.com@app.ptriskyputrakasih.com
          password: ${{ secrets.ftp_password }}
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            README.md
